name: drawing_animation
description: (Migrating to null safety) An dart-only library for gradually painting SVG path objects on canvas (drawing line animation).
version: 0.1.5
repository: https://github.com/biocarl/drawing_animation
homepage: https://twitter.com/cahaucks

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  xml: ^5.2.0
  path_parsing: ^0.2.1
  collection: ^1.15.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  test: ^1.17.11
  mockito: ^5.0.14
  flutter_lints: ^1.0.0
